import AppKit

/// Turns the current pasteboard contents into a `CapturedPayload`, or decides
/// there is nothing worth keeping.
enum PasteboardReader {
    /// Our own UTI for a multi-file selection. The system `public.file-url`
    /// carries one URL per pasteboard item; we flatten the list into one row and
    /// rebuild the items on paste.
    static let fileListType = NSPasteboard.PasteboardType("ee.henno.cbm.file-url-list")

    /// Conventions apps use to say "this is a password" or "this is scratch
    /// data, do not record it". Honouring these is the entire reason a password
    /// never reaches the history.
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.apple.finder.noderef",
    ]

    /// Read in this order; the first three are what make a paste lossless.
    private static let textTypes: [NSPasteboard.PasteboardType] = [.string, .rtf, .html]
    private static let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff]

    /// Chromium writes the page a copy came from here. Chrome, Edge, Brave, Arc
    /// and Opera all share it; Safari offers nothing equivalent, so copies from
    /// Safari keep the application icon.
    private static let chromiumSourceURL = NSPasteboard.PasteboardType("org.chromium.source-url")

    static func read(_ pb: NSPasteboard) -> CapturedPayload? {
        guard let available = pb.types, !available.isEmpty else { return nil }
        if available.contains(where: { ignoredTypes.contains($0.rawValue) }) {
            Log.capture("skipped concealed/transient clipboard")
            return nil
        }

        let sizeCap = Settings.shared.maxItemSizeBytes
        var reps: [Representation] = []
        var oversized = false

        func add(_ type: NSPasteboard.PasteboardType, _ data: Data?) {
            guard let data, !data.isEmpty else { return }
            if data.count > sizeCap { oversized = true; return }
            reps.append(Representation(uti: type.rawValue, data: data))
        }

        // Files first: a Finder copy also carries the path as plain text, and we
        // want it filed as a file entry, not as text.
        let fileURLs = readFileURLs(pb)
        if !fileURLs.isEmpty {
            let joined = fileURLs.map(\.absoluteString).joined(separator: "\n")
            add(fileListType, Data(joined.utf8))
        }

        for type in textTypes { add(type, pb.data(forType: type)) }

        // Read each image type at most once: pulling a screenshot across from
        // the pasteboard server is the single most expensive thing on this path.
        var imageData: Data?
        for type in imageTypes where imageData == nil {
            guard let data = pb.data(forType: type), !data.isEmpty else { continue }
            if data.count > sizeCap {
                oversized = true
                continue
            }
            imageData = data
            reps.append(Representation(uti: type.rawValue, data: data))
        }

        guard !reps.isEmpty else {
            if oversized { Log.capture("skipped clipboard over the \(sizeCap / 1_048_576) MB cap") }
            return nil
        }

        let plain = pb.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines)

        let kind: ItemKind
        if !fileURLs.isEmpty {
            kind = .files
        } else if imageData != nil, plain?.isEmpty ?? true {
            kind = .image
        } else if reps.contains(where: { $0.uti == NSPasteboard.PasteboardType.rtf.rawValue
                                      || $0.uti == NSPasteboard.PasteboardType.html.rawValue }) {
            kind = .rich
        } else {
            kind = .text
        }

        var pixelSize: CGSize?
        if let imageData { pixelSize = ThumbnailMaker.pixelSize(of: imageData) }

        let snippet = makeSnippet(kind: kind, plain: plain, fileURLs: fileURLs, pixelSize: pixelSize)
        guard !snippet.isEmpty else { return nil }

        let front = FrontmostTracker.shared.current
        return CapturedPayload(
            reps: reps,
            kind: kind,
            snippet: snippet,
            sourceBundleID: front.bundleID,
            sourceName: front.name,
            sourceHost: readSourceHost(pb),
            hash: BlobStore.contentIdentity(kind: kind, reps: reps),
            totalBytes: reps.reduce(0) { $0 + $1.data.count },
            pixelSize: pixelSize,
            imageForThumb: imageData)
    }

    /// Keeps only the host. A full URL would turn the history into a log of
    /// every page the user has copied from, which is a much heavier thing to
    /// store than what is needed to show a favicon.
    private static func readSourceHost(_ pb: NSPasteboard) -> String? {
        guard let raw = pb.string(forType: chromiumSourceURL),
              let url = URL(string: raw),
              let scheme = url.scheme?.lowercased(),
              scheme == "http" || scheme == "https",
              let host = url.host, !host.isEmpty
        else { return nil }
        return host.lowercased()
    }

    private static func readFileURLs(_ pb: NSPasteboard) -> [URL] {
        guard let items = pb.pasteboardItems else { return [] }
        var urls: [URL] = []
        for item in items {
            guard let s = item.string(forType: .fileURL), let url = URL(string: s) else { continue }
            urls.append(url)
        }
        return urls
    }

    /// The snippet is both the list label and the entire searchable text, so it
    /// is capped rather than unbounded -- 256 bytes is enough to recognise an
    /// entry and cheap enough to keep thousands of them resident.
    private static let snippetLimit = 256

    private static func makeSnippet(
        kind: ItemKind, plain: String?, fileURLs: [URL], pixelSize: CGSize?
    ) -> String {
        switch kind {
        case .files:
            let names = fileURLs.map { $0.lastPathComponent }.joined(separator: ", ")
            return truncate(names.isEmpty ? "Files" : names)
        case .image:
            if let s = pixelSize, s.width > 0 {
                return "Image \(Int(s.width))×\(Int(s.height))"
            }
            return "Image"
        case .rich, .text:
            let text = plain ?? ""
            if text.isEmpty { return kind == .rich ? "Formatted text" : "" }
            return truncate(text)
        }
    }

    private static func truncate(_ s: String) -> String {
        var bytes = 0
        var out = String.UnicodeScalarView()
        for scalar in s.unicodeScalars {
            let width = UTF8.width(scalar)
            if bytes + width > snippetLimit { break }
            bytes += width
            out.append(scalar)
        }
        return String(out)
    }
}

private extension UTF8 {
    static func width(_ scalar: Unicode.Scalar) -> Int {
        switch scalar.value {
        case 0..<0x80: return 1
        case 0x80..<0x800: return 2
        case 0x800..<0x10000: return 3
        default: return 4
        }
    }
}
